site_name: mocklib
nav:
- Home: home.md
- Advanced: advanced.md
- Structs: structs.md
- Classes: classes.md
- References and Acknowledgements: acknowledgements.md

theme:
  name: null
  custom_dir: 'cinder'
